services:
  2025-autumn-bfi:
    build:
      context: .
      dockerfile: Dockerfile
    image: 2025-autumn-bfi-app
    ports:
      - "8501:8501"
    volumes:
      - .:/project #/src
    environment:
      REPO_ROOT: /project #/src
      DATA_DIR: /project/data
      PYTHONPATH: /project #/src
    shm_size: '16gb'
    # At least one of stdin_open or tty is required to make devcontainer work
    stdin_open: true
    tty: true
    # command: ["tail", "-f", "/dev/null"]